# Generated by Django 5.0.6 on 2026-04-18 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCleanerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_sheet_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('MAPPED', 'Mapped — Awaiting Confirmation'), ('COMPLETED', 'Completed'), ('SUCCESS', 'Analysis Success'), ('FAILED', 'Analysis Fail'), ('REANALYSIS', 'Reanalysis')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaner_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DataCleanerRunPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('analysis_snapshot', models.JSONField(blank=True, default=dict)),
                ('processing_summary', models.JSONField(blank=True, default=dict)),
                ('processed_rows', models.IntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='ingestion.datacleanerrun')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RESTORE', 'Restore'), ('DELETE', 'Delete')], default='DRAFT', max_length=20)),
                ('sheet_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecycleBinSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id_snapshot', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('sheet_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('DELETE', 'Delete'), ('RESTORE', 'Restore')], default='DELETE', max_length=20)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_recycle_actions', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycle_record', to='ingestion.sheet')),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_id', models.BigIntegerField(db_index=True)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('task_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('task_type', models.CharField(max_length=32)),
                ('priority', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('timeframe', models.CharField(max_length=16)),
                ('description', models.TextField(blank=True)),
                ('action', models.TextField(blank=True)),
                ('action_options', models.JSONField(blank=True, default=list)),
                ('product_actions', models.JSONField(blank=True, default=list)),
                ('confidence', models.IntegerField(default=0)),
                ('source', models.CharField(default='analysis', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_records', to='ingestion.datacleanerrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datacleanerrun',
            index=models.Index(fields=['uploaded_by', '-id'], name='dcrun_user_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='datacleanerrun',
            index=models.Index(fields=['analysis_status', '-id'], name='dcrun_status_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='datacleanerrun',
            index=models.Index(fields=['file_hash', 'analysis_status'], name='dcrun_hash_status_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['sheet_id', 'task_type'], name='taskrecord_sheet_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskrecord',
            constraint=models.UniqueConstraint(fields=('sheet_id', 'task_key'), name='unique_task_per_sheet'),
        ),
    ]
