# Generated by Django 5.0.6 on 2026-04-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('sku',)},
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('PRODUCE', 'Produce'), ('BUY', 'Buy'), ('STOP', 'Stop Production'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('timeframe_days', models.IntegerField(default=7)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('explanation', models.TextField()),
                ('action_details', models.TextField(blank=True)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='inventory.product')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.IntegerField(default=10)),
                ('safety_stock', models.IntegerField(default=5)),
                ('max_stock', models.IntegerField(default=500)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Inventory Adjustment'), ('TRANSFER', 'Transfer')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['product', '-transaction_date'], name='inventory_i_product_fc85b0_idx'), models.Index(fields=['transaction_type', '-transaction_date'], name='inventory_i_transac_a5b615_idx'), models.Index(fields=['transaction_type', 'product', '-transaction_date'], name='inventory_trx_tp_pr_dt_idx'), models.Index(fields=['recorded_at'], name='inventory_trx_recorded_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('predicted_demand', models.IntegerField()),
                ('confidence_lower', models.IntegerField(default=0)),
                ('confidence_upper', models.IntegerField(default=0)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('model_used', models.CharField(default='statistical', max_length=50)),
                ('actual_demand', models.IntegerField(blank=True, null=True)),
                ('accuracy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.product')),
            ],
            options={
                'ordering': ['week_start'],
                'unique_together': {('product', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_sheet_name', models.CharField(blank=True, default='', max_length=255)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('on_hand', models.IntegerField(default=0)),
                ('reorder', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=0)),
                ('risk', models.CharField(choices=[('OUT_OF_STOCK', 'Out of Stock'), ('LOW_STOCK', 'Low Stock'), ('DEADSTOCK', 'Deadstock'), ('OVERSTOCK', 'Overstock'), ('HEALTHY', 'Healthy')], db_index=True, max_length=20)),
                ('days_to_stock', models.IntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to='inventory.product')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alert_rows', to='ingestion.datacleanerrun')),
            ],
            options={
                'ordering': ['-updated_at', 'risk', 'name'],
                'indexes': [models.Index(fields=['risk', '-updated_at'], name='inventory_s_risk_1e94fc_idx'), models.Index(fields=['sku'], name='inventory_s_sku_72b221_idx'), models.Index(fields=['run', '-updated_at'], name='stockalert_run_upd_idx')],
            },
        ),
    ]
